### ISSUE TITLE
twitter-v2报错

### ISSUE THREAD

**Issue by ciriue** [Ice9Coffee/HoshinoBot#274]
os：win server 2019
python：3.8.10

config中代理设置为 proxy = http://127.0.0.1:10809

[2023-04-20 18:30:53,017 twitter-poller] INFO: Got twitter event.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\stream.py", line 153, in __anext__
    return await self.restart_stream()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\stream.py", line 266, in restart_stream
    await self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\stream.py", line 110, in connect
    self.response = await self._connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\stream.py", line 92, in _connect
    return await request(timeout=0, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\utils.py", line 115, in __call__
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\utils.py", line 99, in __call__
    return await self.__request(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 543, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 904, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1324, in _create_proxy_connection
    return await self._start_tls_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1094, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1185, in start_tls
    ssl_protocol = sslproto.SSLProtocol(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 421, in __init__
    raise ValueError(
ValueError: ssl_handshake_timeout should be a positive number, got 0

**Comment by Ice9Coffee** [comment]
看起来似乎是代理的问题，检查你的代理节点是否可以正常访问推特

**Comment by Ice9Coffee** [comment]
可能是peony库的问题，尝试将
```
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\peony\stream.py", line 92, in _connect
return await request(timeout=0, **kwargs)
```
这里的`timeout=0`改为一个合理的正实数。
> 我这边由于机器在海外，未使用代理，无法复现该bug。

**Comment by ciriue** [comment]
不对，我换了个节点突然好了，有可能是ip被封了orz，那应该是我的问题，抱歉，打扰了。（滑跪）
